(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const loader=$('#loader'),app=$('#app'),scene=$('#homeScene'),menu=$('#menu'),cursor=$('#cursor'),ripple=$('#ripple');
const AUDIO='https://unseen.co/wp-content/themes/unseen/resources/assets/audio/audio.webm?v=1786625394974';
const sprites={backing:[0,30.747,true],click:[31.2,.5],contact:[32.4,4.5],hover:[37.6,.5],menuClose:[38.8,1],menu:[40,1.071],nav:[42.2,1.567],water:[44.4,2.5],worldStatic:[48.8,5.295],worldIntro:[55,12.8],worldLoop:[68.2,12.8,true]};
let started=false,muted=true,backing=null,current='home',drag=false,sx=0,sy=0,dx=0,dy=0,holdTimer=0,px=0,py=0;
setTimeout(()=>loader.classList.add('ready'),2500);
addEventListener('pointermove',e=>{px=e.clientX;py=e.clientY;const rx=(e.clientX/innerWidth-.5)*10,ry=(e.clientY/innerHeight-.5)*7;$$('.eye b').forEach(p=>p.style.transform=`translate(${rx}px,${ry}px)`);if(matchMedia('(pointer:fine)').matches)cursor.style.transform=`translate3d(${e.clientX-18}px,${e.clientY-18}px,0)`},{passive:true});
function audioAt(name){if(muted||!sprites[name])return;const [s,d]=sprites[name],a=new Audio(AUDIO);a.preload='auto';a.currentTime=s;a.addEventListener('timeupdate',()=>{if(a.currentTime>=s+d){a.pause();a.remove()}});a.play().catch(()=>{});}
function setSound(on){muted=!on;document.body.classList.toggle('sound-on',on);if(on){if(!backing){backing=new Audio(AUDIO);backing.preload='auto';backing.addEventListener('timeupdate',()=>{if(backing.currentTime>=30.65)backing.currentTime=0})}backing.muted=false;backing.play().catch(()=>{})}else if(backing){backing.pause();backing.muted=true}}
function enter(sound){if(started)return;started=true;setSound(sound);app.classList.add('ready');app.setAttribute('aria-hidden','false');loader.classList.add('leave');setTimeout(()=>loader.remove(),1100);if(sound)audioAt('worldStatic')}
$('#enter').onclick=()=>enter(true);$('#silent').onclick=()=>enter(false);$('#sound').onclick=()=>setSound(muted);
function setMenu(open){if(open===menu.classList.contains('open'))return;menu.classList.toggle('open',open);menu.setAttribute('aria-hidden',String(!open));audioAt(open?'menu':'menuClose')}
$$('[data-menu]').forEach(b=>b.addEventListener('click',()=>setMenu(true)));$('#menuClose').onclick=()=>setMenu(false);$('#menuCloseMobile').onclick=()=>setMenu(false);
function syncHash(v){const h=v==='home'?'':`#${v}`;if(location.hash!==h)history.pushState({view:v},'',h||location.pathname)}
function go(v,push=true){const target=$(`.view[data-view="${v}"]`);if(!target)return;$$('.view').forEach(x=>x.classList.toggle('is-active',x===target));current=v;$$('.menuNav button').forEach(b=>b.classList.toggle('active',b.dataset.go===v||(v==='home'&&b.dataset.go==='home')));setMenu(false);if(push)syncHash(v);audioAt(v==='contact'?'contact':v==='world'?'worldIntro':'water');if(v==='world')startWorld();}
$$('[data-go]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();go(b.dataset.go)}));addEventListener('popstate',()=>{const v=location.hash.replace('#','')||'home';go(v,false)});
function pulse(e){const r=scene.getBoundingClientRect();ripple.style.left=`${e.clientX-r.left}px`;ripple.style.top=`${e.clientY-r.top}px`;ripple.classList.remove('go');void ripple.offsetWidth;ripple.classList.add('go')}
scene.addEventListener('pointerdown',e=>{if(e.target.closest('.hot'))return;drag=true;sx=e.clientX;sy=e.clientY;dx=dy=0;pulse(e);cursor.classList.add('hold');scene.setPointerCapture?.(e.pointerId);holdTimer=setTimeout(()=>{if(drag&&Math.hypot(dx,dy)<12)go('projects')},1050)});
scene.addEventListener('pointermove',e=>{if(!drag)return;dx=e.clientX-sx;dy=e.clientY-sy;if(Math.hypot(dx,dy)>8)clearTimeout(holdTimer);if(innerWidth<=700&&Math.abs(dx)>24)scene.classList.add('dragged');const tx=Math.max(-14,Math.min(14,dx*.025)),ty=Math.max(-9,Math.min(9,dy*.016));$$('.homeFrame').forEach((f,i)=>f.style.transform=`scale(1.016) translate3d(${tx*(i?1.08:.8)}px,${ty*(i?1.08:.8)}px,0)`) });
function endDrag(){if(!drag)return;drag=false;clearTimeout(holdTimer);cursor.classList.remove('hold');setTimeout(()=>{$$('.homeFrame').forEach(f=>f.style.transform='')},240)}addEventListener('pointerup',endDrag);addEventListener('pointercancel',endDrag);
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{const f=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));$$('.projectCard').forEach(c=>c.classList.toggle('hide',f!=='all'&&!c.dataset.kind.split(' ').includes(f)));audioAt('click')}));
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));$('.projects').classList.toggle('is-grid',b.dataset.mode==='grid');audioAt('click')}));
const detail=$('#projectDetail');const projectCopy={'Hubtown':'An immersive digital experience for one of India’s leading real estate developers.','Poly':'A playful AI-powered file browser shaped through motion, interaction and three-dimensional form.','Symphony of Vines':'An interactive cinematic journey through the elemental forces behind Bordeaux terroir.','Klook':'A digital experience built around travel, discovery and expressive motion.','KIKK Festival':'A bold identity and digital experience for a festival celebrating art, science and technology.','Digital Experiments':'A collection of self-initiated WebGL, motion and interaction explorations.','BlueYard':'A digital platform shaped around ambitious founders, technology and culture.','25 Residences':'A refined property experience balancing editorial typography and immersive media.','Organimo':'A surreal wellness experience inspired by the sea.','Cosmos':'A visual digital system built around scale, space and motion.','Contra Calculator':'A gamified 3D calculator exploring the economics of independent work.','Clou':'A digital showcase for architecture, space and contemporary design.'};
$$('.projectCard').forEach(c=>c.addEventListener('click',()=>{const title=c.dataset.project,img=c.querySelector('img').src;$('#detailTitle').textContent=title;$('#detailImage').src=img;$('#detailText').textContent=projectCopy[title]||'An immersive digital experience created by Unseen Studio.';detail.classList.add('open');detail.setAttribute('aria-hidden','false');audioAt('water')}));$('#detailBack').onclick=()=>{detail.classList.remove('open');detail.setAttribute('aria-hidden','true')};
let worldStarted=false,ctx,stars=[],yaw=0,pitch=0,wdrag=false,wx=0,wy=0;
function resizeCanvas(){const c=$('#worldCanvas'),dpr=Math.min(2,devicePixelRatio||1);c.width=innerWidth*dpr;c.height=innerHeight*dpr;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0)}
function startWorld(){if(worldStarted)return;worldStarted=true;resizeCanvas();stars=Array.from({length:120},()=>({x:Math.random()*2-1,y:Math.random()*2-1,z:Math.random()*2-1}));requestAnimationFrame(drawWorld)}
function projectPoint(x,y,z){const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);let X=x*cy-z*sy,Z=x*sy+z*cy,Y=y*cp-Z*sp;Z=y*sp+Z*cp;const s=280/(Z+3.4);return [innerWidth/2+X*s,innerHeight/2+Y*s,s]}
function drawWorld(){if(!worldStarted)return;ctx.clearRect(0,0,innerWidth,innerHeight);ctx.strokeStyle='rgba(255,255,255,.19)';ctx.lineWidth=.7;for(let lat=-70;lat<=70;lat+=14){ctx.beginPath();for(let lon=0;lon<=360;lon+=5){const a=lon*Math.PI/180,b=lat*Math.PI/180,[x,y,z]=[Math.cos(b)*Math.cos(a),Math.sin(b),Math.cos(b)*Math.sin(a)],p=projectPoint(x,y,z);lon?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1])}ctx.stroke()}for(let lon=0;lon<360;lon+=14){ctx.beginPath();for(let lat=-90;lat<=90;lat+=5){const a=lon*Math.PI/180,b=lat*Math.PI/180,p=projectPoint(Math.cos(b)*Math.cos(a),Math.sin(b),Math.cos(b)*Math.sin(a));lat>-90?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1])}ctx.stroke()}ctx.fillStyle='rgba(255,255,255,.45)';stars.forEach(s=>{const p=projectPoint(s.x*2.4,s.y*2.4,s.z*2.4);ctx.fillRect(p[0],p[1],1,1)});yaw+=.0007;requestAnimationFrame(drawWorld)}
$('.worldPage').addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;wdrag=true;wx=e.clientX;wy=e.clientY});addEventListener('pointermove',e=>{if(wdrag){yaw+=(e.clientX-wx)*.004;pitch+=(e.clientY-wy)*.003;wx=e.clientX;wy=e.clientY}});addEventListener('pointerup',()=>wdrag=false);addEventListener('resize',()=>{if(worldStarted)resizeCanvas()});
$$('.menuNav button,.siteHeader nav button,.projectCard').forEach(el=>el.addEventListener('mouseenter',()=>audioAt('hover')));addEventListener('keydown',e=>{if(e.key==='Escape'){if(detail.classList.contains('open'))$('#detailBack').click();else setMenu(false)}});
const initial=location.hash.replace('#','')||'home';if(initial!=='home')setTimeout(()=>go(initial,false),40);
})();